version: "2"

services:

  zookeeper:
    image: zookeeper:3.4
    networks:
      - cluster
    environment:
      ZOO_STANDALONE_ENABLED: 'true'

  clickhouse-cluster-1:
    image: yandex/clickhouse-server:19.13.5.44
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse-cluster-1
    networks:
      - cluster
    volumes:
      - ./clickhouse-cluster-conf/conf.d-1/:/etc/clickhouse-server/conf.d/:ro
    depends_on:
      - zookeeper

  clickhouse-cluster-2:
    image: yandex/clickhouse-server:19.13.5.44
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse-cluster-2
    networks:
      - cluster
    volumes:
      - ./clickhouse-cluster-conf/conf.d-2/:/etc/clickhouse-server/conf.d/:ro
    depends_on:
      - zookeeper

  clickhouse-cluster-3:
    image: yandex/clickhouse-server:19.13.5.44
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse-cluster-3
    networks:
      - cluster
    volumes:
      - ./clickhouse-cluster-conf/conf.d-3/:/etc/clickhouse-server/conf.d/:ro
    depends_on:
      - zookeeper

  clickhouse-cluster-4:
    image: yandex/clickhouse-server:19.13.5.44
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    hostname: clickhouse-cluster-4
    networks:
      - cluster
    volumes:
      - ./clickhouse-cluster-conf/conf.d-4/:/etc/clickhouse-server/conf.d/:ro
    depends_on:
      - zookeeper

networks:
  cluster:
    driver: bridge
